### ISSUE TITLE
Add automatization PassConfig for image type

### ISSUE THREAD

**Issue by TomasVotruba** [pehapkari/pehapkari.cz#30]
Follow up to #29

### For grids

```yaml
- { property: 'image', type: 'image', base_path: '%image_uploads%' }
```

### For forms

```yaml
- { property: 'imageFile', type: 'file' }
```

---

```yaml
parameters:
    training_grid_fields:
        - 'name'
        - { property: 'image', type: 'image', base_path: '%image_uploads%' }
        - 'perex'
        - 'description'
        - 'capacity'
        - 'price'
        - 'place'
        - 'trainer'
```
